remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/img/charliebrown.png
title: Michael's Board

sass:
  style: compressed

assets:
  - style.scss
# show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
